### ISSUE TITLE
Cover Art & Diagrams

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/introduction-to-processing#3]
@samalderhyde This new resource from @mrichardson23 will require cover art and a replacement fritzing diagram. Thanks.

**Comment by mrichardson23** [comment]
@samalderhyde Processing is mostly made for visual arts, so artwork, galleries, easels, painters, or palettes might get the idea across well. Ping me if you need more info.

Are you able to add it by end of day Thursday? I think we'll have a blog post about this on Friday. I'd love to include the cover art in the blog post. Thank you!

**Comment by samalderhyde** [comment]
Ok great, I'll get a rough sketch to you today Matt, will push for a final version for Thursday
